# Generated by Django 4.2 on 2023-04-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('descraption', models.CharField(max_length=3000)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('best_seller', models.BooleanField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(verbose_name=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='appwoter.category')),
            ],
        ),
    ]
