# Generated by Django 4.2 on 2023-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.FloatField(choices=[('cash', 'Cash'), ('free', 'Free'), ('exchange', 'Exchange')]),
        ),
    ]
