# Generated by Django 4.2 on 2023-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwoter', '0003_sell_choise_type_price_alter_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='number',
        ),
        migrations.AddField(
            model_name='sell',
            name='phonr_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
