# Generated by Django 4.2 on 2023-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwoter', '0004_remove_sell_number_sell_phonr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='choise_type_price',
            field=models.CharField(choices=[('cash', 'Cash'), ('free', 'Free'), ('exchange', 'Exchange')], max_length=50),
        ),
    ]
