# Generated by Django 4.2 on 2023-04-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwoter', '0005_alter_sell_choise_type_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
