# Generated by Django 4.2 on 2023-04-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appwoter', '0006_remove_sell_category_delete_category_delete_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('deccraption', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('day', models.IntegerField()),
                ('documents', models.TextField()),
                ('price', models.FloatField()),
                ('farmname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='appwoter.category')),
            ],
        ),
    ]
