# Generated by Django 4.2 on 2023-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwoter', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
